"""
analyze/initialize/platform_handlers.py
=========================================
Per-platform logic that resolves the source files and split strategy for
a single roadshow, returning a :class:`VideoSplitPlan`.

A VideoSplitPlan describes *how* to produce the two output clips:

    v1 (推介致辞)  —  main presentation speech
    v2 (答谢致辞)  —  closing thank-you speech

Supported modes
---------------
SEPARATE
    v1_sources / v2_sources each hold one or more source paths to
    concatenate.  Used for 上证, 中国证券网, and most 中证 companies.

SPLIT
    full_source is a single complete-roadshow file that must be cut at
    ``split_time`` seconds.  Used for 全景, IR, and 中证 companies whose
    录制 is a single 完整视频.

Public entry point
------------------
resolve_split_plan(row_data, cscom_plans) -> VideoSplitPlan
"""

from __future__ import annotations

import csv
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

# Make analyze/ importable
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from config import get_video_dir, PROJECT_ROOT

from .cscom_plan import CscomCompanyPlan

# ── Split-windows table ────────────────────────────────────────────────────────
# Generated by gen_split_windows.py, reviewed by the user, then consumed here.
SPLIT_WINDOWS_PATH: Path = PROJECT_ROOT / "tmp" / "video_split_windows.csv"


# ── Data model ─────────────────────────────────────────────────────────────────

@dataclass
class VideoSplitPlan:
    """
    Describes how to produce the (v1, v2) output pair for one roadshow.

    Either ``v1_sources / v2_sources`` are populated (SEPARATE mode)
    or ``full_source`` is set (SPLIT mode) — never both.

    SPLIT mode fields
    -----------------
    full_source   : single complete video to be cut.
    v1_start_sec  : start of 推介致辞 clip (seconds from video start).
                    Defaults to 0.0 (skip nothing).
    split_time    : start of 答谢致辞 clip = end of 推介致辞 clip.
                    None → skip splitting (video has no 答谢致辞).
    v2_end_sec    : end of 答谢致辞 clip.  None → cut to EOF.
    """
    index2009: str
    code: str
    date: str
    platform: str

    # SEPARATE mode
    v1_sources: list[Path] = field(default_factory=list)
    v2_sources: list[Path] = field(default_factory=list)

    # SPLIT mode
    full_source:  Path | None  = None
    v1_start_sec: float        = 0.0       # 推介致辞 clip start
    split_time:   float | None = None      # 答谢致辞 clip start (split boundary)
    v2_end_sec:   float | None = None      # 答谢致辞 clip end; None = EOF

    @property
    def is_split_mode(self) -> bool:
        return self.full_source is not None

    def validate(self) -> list[str]:
        """Return a list of warning strings for missing files."""
        warnings: list[str] = []
        if self.is_split_mode:
            if self.full_source and not self.full_source.exists():
                warnings.append(f"完整视频不存在: {self.full_source}")
        else:
            for p in self.v1_sources:
                if not p.exists():
                    warnings.append(f"推介视频不存在: {p}")
            for p in self.v2_sources:
                if not p.exists():
                    warnings.append(f"答谢视频不存在: {p}")
        return warnings


# ── Split-windows table loader ─────────────────────────────────────────────────

def load_split_windows(path: Path | None = None) -> dict[str, dict]:
    """
    Load ``tmp/video_split_windows.csv`` (or *path*) into a dict keyed by
    ``index2009``.  Returns an empty dict if the file does not exist.

    Only rows where ``needs_manual == 0`` and ``v2_start_sec`` is non-empty
    are considered actionable; all rows are returned so callers can decide.
    """
    csv_path = path or SPLIT_WINDOWS_PATH
    if not csv_path.exists():
        return {}
    windows: dict[str, dict] = {}
    try:
        with open(csv_path, encoding="utf-8-sig") as f:
            for row in csv.DictReader(f):
                idx = row.get("index2009", "").strip()
                if idx:
                    windows[idx] = row
    except Exception as e:
        print(f"[WARN] split_windows 表读取失败: {csv_path} — {e}")
    return windows


def _apply_split_windows(plan: VideoSplitPlan, windows: dict[str, dict]) -> None:
    """
    Populate *plan* SPLIT-mode boundary fields from the validated table.

    Silently does nothing when the index2009 is absent from the table or
    when v2_start_sec is empty (indicates a row still needing manual review).
    """
    w = windows.get(plan.index2009)
    if w is None:
        return

    def _f(key: str) -> float | None:
        val = w.get(key, "").strip()
        if val == "":
            return None
        try:
            return float(val)
        except ValueError:
            return None

    v1 = _f("v1_start_sec")
    v2 = _f("v2_start_sec")
    ve = _f("v2_end_sec")

    if v2 is None:
        # v2 missing → flag still needs manual review; leave split_time=None
        # so the worker falls back to runtime transcript detection
        return

    plan.split_time   = v2
    plan.v2_end_sec   = ve
    if v1 is not None:
        plan.v1_start_sec = v1


# ── Helpers ────────────────────────────────────────────────────────────────────

def _extract_seg_number(path: Path) -> int:
    m = re.search(r"_视频(\d+)", path.name)
    return int(m.group(1)) if m else 999


# ── Per-platform handlers ──────────────────────────────────────────────────────

def _plan_shangzheng(
    index2009: str, code: str, date: str, platform: str
) -> VideoSplitPlan:
    """
    上证 / 中国证券网: files are already labelled _视频1_ (推介) and _视频2_
    (答谢).  Both clips are used directly — no merging needed.
    """
    video_dir = get_video_dir(platform)
    plan = VideoSplitPlan(
        index2009=index2009, code=code, date=date, platform=platform
    )

    seg_map: dict[int, Path] = {}
    for vf in video_dir.glob(f"{code}_*_{date}_视频*.mp4"):
        m = re.search(r"_视频(\d+)", vf.name)
        if m and m.group(1) in ("1", "2"):
            seg_map[int(m.group(1))] = vf

    if 1 in seg_map:
        plan.v1_sources = [seg_map[1]]
    else:
        print(
            f"[WARN] 未找到推介致辞(视频1): "
            f"index={index2009} code={code} date={date} platform={platform}"
        )
    if 2 in seg_map:
        plan.v2_sources = [seg_map[2]]
    else:
        print(
            f"[WARN] 未找到答谢致辞(视频2): "
            f"index={index2009} code={code} date={date} platform={platform}"
        )

    return plan


def _plan_cscom(
    index2009: str,
    code: str,
    date: str,
    cscom_plans: dict[str, dict],
    split_windows: dict[str, dict] | None = None,
) -> VideoSplitPlan:
    """
    中证: use the pre-built company plan from ``cscom_plan.py``.

    - SEPARATE mode for companies with explicit 推介/答谢 labels.
    - SPLIT mode for companies with a single 完整视频 that needs cutting.
    """
    video_dir = get_video_dir("中证")
    plan = VideoSplitPlan(
        index2009=index2009, code=code, date=date, platform="中证"
    )

    raw = cscom_plans.get(code)
    if raw is None:
        print(f"[WARN] 中证分类表中无此公司: code={code}")
        return plan

    company_plan = CscomCompanyPlan.from_dict(raw)

    if company_plan.needs_split:
        full_path = video_dir / company_plan.full_filename
        plan.full_source = full_path
        if not full_path.exists():
            print(f"[WARN] 中证完整视频不存在: {full_path}")
        if split_windows:
            _apply_split_windows(plan, split_windows)
    else:
        plan.v1_sources = [
            video_dir / fn for fn in company_plan.v1_filenames
        ]
        plan.v2_sources = [
            video_dir / fn for fn in company_plan.v2_filenames
        ]

        if not plan.v1_sources:
            print(
                f"[WARN] 中证无推介致辞源文件: "
                f"index={index2009} code={code}"
            )
        if not plan.v2_sources:
            print(
                f"[WARN] 中证无答谢致辞源文件: "
                f"index={index2009} code={code}"
            )

    return plan


def _plan_split_full(
    index2009: str, code: str, date: str, platform: str,
    split_windows: dict[str, dict] | None = None,
) -> VideoSplitPlan:
    """
    全景 / IR: single complete-roadshow file → SPLIT mode.

    Split boundaries (v1_start_sec, split_time, v2_end_sec) are loaded
    from video_split_windows.csv via split_windows.
    """
    video_dir = get_video_dir(platform)
    plan = VideoSplitPlan(
        index2009=index2009, code=code, date=date, platform=platform
    )

    candidates = [
        vf for vf in video_dir.glob(f"{code}_*_{date}*.mp4")
        if "宣传片" not in vf.name
    ]

    if not candidates:
        print(
            f"[WARN] 未找到视频文件: "
            f"index={index2009} code={code} date={date} platform={platform}"
        )
        return plan

    if len(candidates) > 1:
        # Sort by video number; take the first (usually part 1 of a split)
        candidates.sort(key=_extract_seg_number)
        print(
            f"[WARN] 找到{len(candidates)}个视频，取视频号最小者: "
            f"{[c.name for c in candidates]}"
        )

    plan.full_source = candidates[0]

    if split_windows:
        _apply_split_windows(plan, split_windows)

    return plan


# ── Public entry point ─────────────────────────────────────────────────────────

def resolve_split_plan(
    row_data: dict,
    cscom_plans: dict[str, dict],
    split_windows: dict[str, dict] | None = None,
) -> VideoSplitPlan:
    """
    Dispatch to the correct platform handler and return a
    :class:`VideoSplitPlan`.

    Parameters
    ----------
    row_data : dict
        Must contain: ``platform``, ``index2009``, ``code``, ``date``.
    cscom_plans : dict
        Pre-loaded 中证 plans from :func:`~.cscom_plan.load_cscom_plans`.
    split_windows : dict, optional
        Pre-loaded split-window boundaries from ``video_split_windows.csv``,
        keyed by ``index2009``.  When provided, SPLIT-mode plans receive
        pre-validated v1_start_sec / split_time / v2_end_sec values directly
        instead of relying on runtime transcript detection.
    """
    platform  = row_data["platform"]
    index2009 = row_data["index2009"]
    code      = row_data["code"]
    date      = row_data["date"]
    sw        = split_windows or {}

    if platform in ("上证", "中国证券网"):
        return _plan_shangzheng(index2009, code, date, platform)
    elif platform == "中证":
        return _plan_cscom(index2009, code, date, cscom_plans, sw)
    elif platform in ("全景", "IR"):
        return _plan_split_full(index2009, code, date, platform, sw)
    else:
        print(f"[WARN] 未知平台: {platform}")
        return VideoSplitPlan(
            index2009=index2009, code=code, date=date, platform=platform
        )
